### PR TITLE
Added repository property in package.json

### PR DESCRIPTION
**Pull request by rgabs**
Added repository property in package.json to make the Github link visible on NPM website.

### CODE REVIEW

**Comment by Haroenv** [comment]
It originally wasn't set, when the repository was private, thanks for adding it!

**Comment by tkrugg** [comment]
This PR build is failing because of the private env variables we have on travis.
@JonasBa is there something we can do about it to allow external contribution PR to be checked?

**Comment by tkrugg** [comment]
will be merged here: https://github.com/algolia/search-insights.js/pull/52

**Comment by tkrugg** [comment]
your contribution has landed @rgabs 🎉in our [develop branch. ](https://github.com/algolia/search-insights.js/commits/develop)
Thank you very much!

**Pull request closed without merging**
