### PR TITLE
chore(deps): update stuff

### PR DESCRIPTION
**Pull request by tkrugg**

### CODE REVIEW

**Comment by samouss** [comment]
Enable Renovate?

**Comment by tkrugg** [comment]
yep, asked for it to the IT teams, I don't think I'm able to do it by myself on @algolia repos

**Comment by samouss** [comment]
I might be wrong but I think Renovate is enabled on all the Algolia repo. You only have to create the `renovate.json` file. It will then create a PR to setup the configuration.

**Comment by tkrugg** [comment]
Oh didn't know that.
Ok I just added it. Thanks!

**Pull request closed without merging**
