### PR TITLE
feat(api): add host to the initial params

### PR DESCRIPTION
**Pull request by goonca**
solution for: https://support.algolia.com/hc/en-us/requests/545695

### CODE REVIEW

**Comment by benhinchley** [comment]
Hi @goonca thanks for making this change, I'll have a look at the linked ticket and this change this week.

**Review by wwalser — APPROVED** [review]

**Comment by wwalser** [comment]
LGTM, please check out the lint error which has to do with code formatting. Should be able to setup your editor to do that for you or you can fix it manually if this is a code base that you don't use often.

**Comment by goonca** [comment]
I had to decouple the assignment of the initial params from the init function because it violated the lint complexity rule

**Review by wwalser — APPROVED** [review]

**Comment by goonca** [comment]
@benhinchley what are the steps now?

**Comment by wwalser** [comment]
Ben is on vacation for a while. 
@JasonBerry should we get this in with our v3 or can we push it out in a dot version of v2?

**Comment by JasonBerry** [comment]
> Ben is on vacation for a while. @JasonBerry should we get this in with our v3 or can we push it out in a dot version of v2?

Can go out in a minor release. We'll add it to our v3 also.

**Review by JasonBerry — APPROVED** [review]
Hi @goonca,

I applied a small fix to the context of the `assignInitialParams` function and added a test. I'll merge this and get it released ASAP.

Thanks!

**Pull request merged**
